### PR TITLE
Fixed #8

### LINKED ISSUE #8: Make tests pass when no proxy configured
If you do not have a proxy configured using System Properties then HttpClientExamples fails.

### PR DESCRIPTION
**Pull request by ralphcollett**
Fixed #8. You can now run a build without a Proxy configured via system properties.

### CODE REVIEW

**Comment by tobyweston** [comment]
Good stuff, thanks. You have rights to merge yourself dont you?

**Comment by ralphcollett** [comment]
I thought so but wasn’t working for me. Does it look like I should your end?

**Comment by tobyweston** [comment]
It's 'cos you forked first. You have committer writes to the main project so can just clone from there and delete your fork. ttfn

**Comment by ralphcollett** [comment]
Ok, I did try cloning first which didn’t work when I tried to push. I probably missed something. Cheers

**Pull request merged**
